name: Run ASCII Script
on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Make the script executable and run it
      - name: Execute ASCII Script
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh

      # Step 3: Display the output of dragon.txt
      - name: Display dragon.txt
        run: cat dragon.txt


# Longer method which is still valid way 

      # - name: Install Cowsay Program
      #   run: sudo apt-get install cowsay -y

      # - name: Execute Cowsay CMD
      #   run: cowsay -f dragon "Run for cover, I am a dragon......RAWR" >> dragon.txt

      # - name: Check File Exists
      #   run: grep -i dragon "dragon.txt"

      # - name: Read File
      #   run: cat dragon.txt

      # - name: List Repos Files
      #   run: ls -ltra


    #   fixing the issue