name: Generate ascii artwork
on: push
jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3


      - name: List Repos Files
        run: ls -ltra

# Scripts are used to make the workflow easeir to manage 
      - name: Executing Shell Script
        run: |
          chmod +x script.sh
          ../script.sh