name: Node.js Workflow
on: push
jobs:
  node_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check Node.js version
        run: node -v

      - name: Create and run a JavaScript file
        run: |
          echo "console.log('Hello from Node.js');" > hello.js
          node hello.js
