name: Docker Workflow with Secrets
on: push

env:  # Workflow-level environment variables, including secrets
  DOCKER_IMAGE: nginx:latest
  CONTAINER_NAME: my-nginx-container
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker_job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 2: Pull the Docker image
      - name: Pull Docker Image
        run: docker pull $DOCKER_IMAGE

      # Step 3: Run the Docker container
      - name: Run Docker Container
        run: |
          docker run -d --name $CONTAINER_NAME -p 8080:80 $DOCKER_IMAGE

      # Step 4: List running containers
      - name: List Running Containers
