name: Docker Workflow with Secrets
on: push

env:  # Workflow-level environment variables
  DOCKER_IMAGE: nginx:latest
  CONTAINER_NAME: my-nginx-container
  CONTAINER_REGISTRY: docker.io  # Assuming Docker Hub is used as the registry

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository (if needed)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password=${{ secrets.DOCKER_PASSWORD}}

      # Step 3: Build Docker Image
      - name: Docker Build
        run: |
          docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE .

      # Step 4: Push Docker Image to Registry
      - name: Docker Publish
        run: |
          docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      # Step 1: Run Docker Container
      - name: Docker Run
        run: |
          docker run -d --name $CONTAINER_NAME -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE
